#!/usr/bin/env bash
set -euo pipefail

WORKDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PYTHON_BIN="${PYTHON_BIN:-${WORKDIR}/venv/bin/python3}"

if [[ ! -x "${PYTHON_BIN}" ]]; then
  PYTHON_BIN="python3"
fi

echo "Cleaning up stale Glassdoor runs..."
rm -f "${WORKDIR}/outputs/scrape_run.lock"

cd "${WORKDIR}"
if [[ -f "${WORKDIR}/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "${WORKDIR}/.env"
  set +a
fi

JOB_WATCH_SOURCES="${JOB_WATCH_SOURCES:-glassdoor_uae}"
export JOB_WATCH_SOURCES
export BROWSER_BATCH_WORKERS="${BROWSER_BATCH_WORKERS:-1}"
export BROWSER_GLASSDOOR_BATCH_SIZE="${BROWSER_GLASSDOOR_BATCH_SIZE:-1}"
export BROWSER_GLASSDOOR_BATCH_WORKERS="${BROWSER_GLASSDOOR_BATCH_WORKERS:-1}"
export BROWSER_PROBE_HEARTBEAT_SECONDS="${BROWSER_PROBE_HEARTBEAT_SECONDS:-10}"
export SKIP_LINKEDIN_BROWSER="${SKIP_LINKEDIN_BROWSER:-1}"
export SKIP_INDEED_BROWSER="${SKIP_INDEED_BROWSER:-1}"
export SKIP_JOBSPY="${SKIP_JOBSPY:-1}"

if command -v caffeinate >/dev/null 2>&1; then
  exec caffeinate -s env \
    JOB_WATCH_SOURCES="${JOB_WATCH_SOURCES}" \
    SKIP_NEWS_COLLECTION="1" \
    SKIP_LINKEDIN_BROWSER="${SKIP_LINKEDIN_BROWSER}" \
    SKIP_INDEED_BROWSER="${SKIP_INDEED_BROWSER}" \
    SKIP_JOBSPY="${SKIP_JOBSPY}" \
    BROWSER_BATCH_WORKERS="${BROWSER_BATCH_WORKERS}" \
    BROWSER_GLASSDOOR_BATCH_SIZE="${BROWSER_GLASSDOOR_BATCH_SIZE}" \
    BROWSER_GLASSDOOR_BATCH_WORKERS="${BROWSER_GLASSDOOR_BATCH_WORKERS}" \
    BROWSER_PROBE_HEARTBEAT_SECONDS="${BROWSER_PROBE_HEARTBEAT_SECONDS}" \
    "${PYTHON_BIN}" src/watch/glassdoor_batch.py
fi

exec env \
  JOB_WATCH_SOURCES="${JOB_WATCH_SOURCES}" \
  SKIP_NEWS_COLLECTION="1" \
  SKIP_LINKEDIN_BROWSER="${SKIP_LINKEDIN_BROWSER}" \
  SKIP_INDEED_BROWSER="${SKIP_INDEED_BROWSER}" \
  SKIP_JOBSPY="${SKIP_JOBSPY}" \
  BROWSER_BATCH_WORKERS="${BROWSER_BATCH_WORKERS}" \
  BROWSER_GLASSDOOR_BATCH_SIZE="${BROWSER_GLASSDOOR_BATCH_SIZE}" \
  BROWSER_GLASSDOOR_BATCH_WORKERS="${BROWSER_GLASSDOOR_BATCH_WORKERS}" \
  BROWSER_PROBE_HEARTBEAT_SECONDS="${BROWSER_PROBE_HEARTBEAT_SECONDS}" \
  "${PYTHON_BIN}" src/watch/glassdoor_batch.py
